version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: test
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4 
    image: dpage/pgadmin4
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8081:80"